name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.AWS_EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-15-228-59-223.sa-east-1.compute.amazonaws.com << 'EOF'
        cd /path/to/your/project
        git pull
        docker build -t yourapp .
        docker stop yourapp || true && docker rm yourapp || true
        docker run -d -p 8000:8000 --name yourapp yourapp
        EOF
